version: '2'

services:
  nginx-proxy:
    restart: always
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    restart: always
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    #network_mode: bridge
    #networks:
    #  - proxy-tier

  laingame-php:
    build: containers/php-fpm
    restart: always
    expose:
      - "9000"
    environment:
      LANG: "C.UTF-8"
    working_dir: /var/www/laingame.net
    volumes:
      - ../../:/var/www/laingame.net
    depends_on:
      - laingame-mysql

  laingame-mysql:
    restart: always
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    security_opt:
      - label:disable
    expose:
      - "3306"
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_USER: 'lain'
      MYSQL_DATABASE: 'laingame'
      MYSQL_PASSWORD: 'p4ssp4ss'
      MYSQL_ROOT_PASSWORD: 'p4ssp4ss'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      LANG: "C.UTF-8"
    volumes:
      - ../../database/laingame.sql:/docker-entrypoint-initdb.d/0_init.sql

  laingame-nginx:
    restart: always
    image: nginx:alpine
    expose:
      - "80"
    #ports:
    #  - "${NGINX_PORT}:80"
    #  - "${SSL_PORT}:443"
    depends_on:
      - laingame-php
    volumes:
      - ./config/nginx/vhost:/etc/nginx/conf.d
    volumes_from:
      - laingame-php
    environment:
      - VIRTUAL_HOST=raw.laingame.net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=raw.laingame.net
      - LETSENCRYPT_EMAIL=laingame.net@gmail.com

#  node:
#    build: containers/node
#    restart: "no"
#    environment:
#      LANG: "C.UTF-8"
#    working_dir: /var/www/laingame.net
#    volumes_from:
#      - laingame-php

volumes:
  mysql:
    driver: local
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:

networks:
  default:
    external:
      name: nginx-proxy
